### ISSUE TITLE
RAWv2-slow will regularily set the sensor to unavailable

### ISSUE THREAD

**Issue by makuser** [ruuvi-friends/ruuvi-hass.io#11] opened 2020-11-19 13:00 UTC
After switching from RAWv2-fast to RAWv2-slow for some of the RuuviTags in order to save some battery lifetime, the sensors in HASS start to have larger gaps in the graphs, because their entities are set to `unknown` every few updates or so, instead of simply not updating the entities and possibly marking them as "unavailable" after some time, the current behavior will disrupt the history graphs.

**Comment by sergioisidoro** [comment] 2020-11-21 14:01
Hi @makuser , is this issue related with https://github.com/ruuvi-friends/ruuvi-hass.io/pull/4 ?

**Comment by makuser** [comment] 2020-11-21 14:10
> Hi @makuser , is this issue related with #4 ?

Well it might be, that fixing #4 could help with this, to avoid the "small gaps" in the graps that you described.
But in even in general, a HASS component should not send 'unknown' as a value, but instead mark the sensor as unavailable, if necessary.

#4 additionally proposes to introduce a "data holding period", that I think might not even be necessary in this case.

So yeah, you can mark it as dup of #4 if you think that it is, otherwise you can leave it open and I will see if what you come up in #4 will also fix the issue with RuuviTags in `RAWv2-slow` mode.

**Comment by sergioisidoro** [comment] 2020-11-21 14:35
Let's keep it open. I also have to dig if there has been any updates to the sensor api in Home Assistant, because I don't remember having this problem. As you saw in #4 previously if a sensor got our of range or not found, hass would just assume the previous value. I asked about this on the Discord and it seemed to be the expected behavior at the time, and that's the reason why I made that draft pr.

**Comment by sergioisidoro** [comment] 2021-03-12 20:25
This should now be fixed by #14 .

**Closed by sergioisidoro** 2021-03-12 20:25 UTC
